---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "argocd"
    openshift.io/display-name: "argocd"
  name: argocd
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ArgoCD.v1alpha1.argoproj.io
  name: argocd
  namespace: argocd
spec:
  targetNamespaces:
    - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator-helm
  namespace: argocd
spec:
  channel: alpha
  name: argocd-operator-helm
  source: community-operators
  sourceNamespace: openshift-marketplace
